import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
// @ts-expect-error — .mjs helper shared with scripts/make-og.mjs (no types; plain JS by design)
import { ogStamp } from '../scripts/lib/ogStamp.mjs'
import { brandBadgeHtml } from '../app/config/brandBadge'
import { LANDING_FORMATS, LANDING_SUBTITLE, LANDING_TITLE } from '../app/utils/landing'

// Guard against the exact failure of #329: `public/og.png` is a committed binary regenerated by a
// MANUAL `pnpm og`, so PR #325 could change the landing copy and leave the live share card showing
// the old subtitle and the retired «1С». Nothing was watching. Now the generator stamps a hash of
// its inputs next to the PNG, and this test recomputes it — a copy edit without a rebuild fails CI.
//
// Not mtime-based on purpose: git does not preserve modification times, so on a fresh clone (i.e.
// every CI run) the PNG and its sources are equally «new» and a freshness check would prove nothing.
const BADGE_SCALE = 2.2 // must mirror scripts/make-og.mjs — asserted below

describe('карточка шаринга пересобрана под текущие тексты (#329)', () => {
  const script = readFileSync(new URL('../scripts/make-og.mjs', import.meta.url), 'utf8')

  it('og.stamp.json совпадает с хэшем текущих исходников — иначе нужен `pnpm og`', () => {
    const stamp = JSON.parse(readFileSync(new URL('../public/og.stamp.json', import.meta.url), 'utf8'))
    const expected = ogStamp({
      title: LANDING_TITLE,
      subtitle: LANDING_SUBTITLE,
      formats: LANDING_FORMATS,
      badge: brandBadgeHtml('Bitrix24', 'Приложение', BADGE_SCALE)
    })
    expect(
      stamp.hash,
      'Тексты лендинга или хром бейджа изменились, а public/og.png не пересобрана: запустите `pnpm og` и закоммитьте картинку вместе со штампом.'
    ).toBe(expected.hash)
  })

  it('масштаб бейджа в тесте и в генераторе — одно число', () => {
    expect(script).toContain(`const BADGE_SCALE = ${BADGE_SCALE}`)
  })

  it('подвал карточки берётся из LANDING_FORMATS, а не печатается руками', () => {
    // Ровно это расхождение и оставило «1С» на живой картинке после #325: список форматов был
    // третьей рукописной копией. Проверяем ТОЛЬКО html-шаблон — комментарии в шапке скрипта
    // законно упоминают снятый бренд, объясняя, что здесь произошло.
    const template = script.slice(script.indexOf('const html = '), script.indexOf('</body></html>'))
    expect(template).toContain('LANDING_FORMATS.join')
    expect(template).not.toMatch(/1[СC]\b/) // ни кириллическая «1С», ни латинская «1C»
  })

  it('надзаголовок — общий бейдж, а не плоская строка', () => {
    expect(script).toContain('brandBadgeHtml(')
    expect(script).not.toContain('class="eyebrow"')
  })
})
