import { createHash } from 'node:crypto'
import { readFileSync, readFileSync as nodeReadFileSync } from 'node:fs'
import { dirname as nodeDirname, join as nodeJoin } from 'node:path'
import { describe, expect, it } from 'vitest'
// @ts-expect-error — .mjs helpers shared with scripts/make-og.mjs (plain JS by design, no types)
import { ogStamp } from '../scripts/lib/ogStamp.mjs'
// @ts-expect-error — see above
import { buildOgHtml } from '../scripts/lib/ogTemplate.mjs'
import { LANDING_DESCRIPTION, LANDING_FORMATS } from '../app/utils/landing'

// Guard against the exact failure of #329: `public/og.png` is a committed binary regenerated by a
// MANUAL `pnpm og`, so PR #325 could change the landing copy and leave the live share card showing
// the old subtitle and the retired «1С». Nothing was watching.
//
// The stamp fingerprints BOTH sides of the render: the finished markup (copy + layout + colours +
// badge + inlined logo — anything that changes the pixels) and the produced PNG itself. Copy-only
// hashing was not enough: tuning the card's CSS, or reverting just the image with
// `git checkout main -- public/og.png`, would each have restored the symptom silently.
//
// Not mtime-based on purpose: git does not preserve modification times, so on a fresh clone (i.e.
// every CI run) the PNG and its sources are equally «new» and a freshness check would prove nothing.
const png = readFileSync(new URL('../public/og.png', import.meta.url))
const stamp = JSON.parse(readFileSync(new URL('../public/og.stamp.json', import.meta.url), 'utf8'))

describe('карточка шаринга пересобрана под текущие исходники (#329)', () => {
  it('разметка карточки совпадает со штампом — иначе нужен `pnpm og`', async () => {
    const expected = ogStamp(await buildOgHtml(), png)
    expect(
      stamp.hash,
      'Тексты, вёрстка или бейдж карточки изменились, а public/og.png не пересобрана: запустите `pnpm og` и закоммитьте картинку вместе со штампом.'
    ).toBe(expected.hash)
  })

  it('сама картинка — та, которую сгенерировал этот штамп', () => {
    // Ловит откат/битый мерж, тронувший ТОЛЬКО png: исходники сойдутся, а пиксели будут чужие.
    expect(
      stamp.png,
      'public/og.png не соответствует штампу — картинку заменили мимо генератора; запустите `pnpm og`.'
    ).toBe(createHash('sha256').update(png).digest('hex'))
  })
})

describe('содержимое карточки собрано из общих источников, а не напечатано руками', () => {
  it('подвал — LANDING_FORMATS, и никакой «1С»', async () => {
    // Ровно это расхождение и оставило «1С» на живой картинке после #325: список форматов был
    // третьей рукописной копией. Проверяем РЕЗУЛЬТАТ сборки, а не текст скрипта.
    const html = await buildOgHtml()
    expect(html).toContain(LANDING_FORMATS.join(' · '))
    expect(html).not.toMatch(/1[СC]\b/)
  })

  it('на карточке короткое описание, а не 195-знаковый подзаголовок', async () => {
    // В ленте карточку показывают шириной ~500px: четыре строки мелкого текста читать не будут.
    expect(await buildOgHtml()).toContain(LANDING_DESCRIPTION)
  })

  it('надзаголовок — общий бейдж (пилюля), а не плоская строка', async () => {
    const html = await buildOgHtml()
    expect(html).toContain('Bitrix24')
    expect(html).toContain('border-radius') // хром пилюли из brandBadgeHtml
    expect(html).not.toContain('class="eyebrow"')
  })
})

// ⚠ Цепочка генератора карточки обязана быть alias-free ТРАНЗИТИВНО (#412).
//
// `pnpm og` гоняет `scripts/lib/ogTemplate.mjs` через голый `node --experimental-strip-types`, где
// алиасов Nuxt нет: один импорт по `~/` в любом файле цепочки роняет команду с `Cannot find
// package '~'`. И это не гипотеза — так `pnpm og` не запускался ВООБЩЕ до #412, то есть
// единственный документированный способ починить красный штамп сам был сломан. Тесты этого не
// видят: сюда `ogTemplate.mjs` приезжает через Vite, где `~/` резолвится штатно.
describe('#412: генератор карточки не зависит от алиасов Nuxt', () => {
  it('вся цепочка импортов — относительные пути с расширением', () => {
    const root = new URL('../', import.meta.url).pathname
    const seen = new Set<string>()
    const bad: string[] = []
    const walk = (file: string) => {
      if (seen.has(file)) return
      seen.add(file)
      const src = nodeReadFileSync(file, 'utf8')
      for (const m of src.matchAll(/from\s+'([^']+)'/g)) {
        const spec = m[1]!
        if (spec.startsWith('node:')) continue
        if (!spec.startsWith('.')) {
          // Пакет из node_modules — норма. Алиас — нет: у `node` он не резолвится.
          if (spec.startsWith('~') || spec.startsWith('@/')) bad.push(`${file.replace(root, '')}: ${spec}`)
          continue
        }
        if (!/\.(ts|mjs|js)$/.test(spec)) {
          // Без расширения `node` тоже не найдёт файл — Vite бы нашёл, и рассинхрон был бы немым.
          bad.push(`${file.replace(root, '')}: ${spec} — без расширения`)
          continue
        }
        walk(nodeJoin(nodeDirname(file), spec))
      }
    }
    walk(nodeJoin(root, 'scripts/lib/ogTemplate.mjs'))
    expect(bad, `цепочка pnpm og сломается на node:\n${bad.join('\n')}`).toEqual([])
    // Мета-проверка: обход действительно дошёл до файлов приложения, а не остановился на первом.
    expect([...seen].some(f => f.includes('app/utils/landing.ts'))).toBe(true)
  })
})
