import { createHash } from 'node:crypto'

// Fingerprint of everything the share card is rendered FROM (#329).
//
// `public/og.png` is a committed binary regenerated by a MANUAL `pnpm og`. Nothing forced anyone to
// run it, so a copy edit could ship with a stale card — that is how PR #325 left the old subtitle
// and the retired «1С» on the live image while the site already said otherwise.
//
// The generator writes this stamp next to the PNG; `tests/ogStamp.test.ts` recomputes it from the
// current sources and fails when they diverge, i.e. «you edited the copy, re-run pnpm og».
// Deliberately NOT mtime-based: git does not preserve modification times, so after a fresh clone
// (every CI run) the PNG and its inputs are all equally «new» and such a guard proves nothing.
//
// Hashes the FINISHED markup, not just the copy: layout, colours, badge chrome and the inlined logo
// all change what the PNG looks like, and a copy-only hash would have let a template edit ship stale
// pixels. Both sides build that markup with the same `buildOgHtml` (scripts/lib/ogTemplate.mjs), so
// the hash cannot be computed two slightly different ways.
export function ogStamp(html, pngBytes) {
  return {
    hash: createHash('sha256').update(html).digest('hex'),
    // …and a digest of the produced image. Without it the stamp only proves «the sources match what
    // the sources were», so a revert or bad merge that touches ONLY public/og.png (say
    // `git checkout main -- public/og.png`) restores the exact #329 symptom with every test green.
    png: createHash('sha256').update(pngBytes).digest('hex')
  }
}
