import { createHash } from 'node:crypto'

// Fingerprint of everything the share card is rendered FROM (#329).
//
// `public/og.png` is a committed binary regenerated by a MANUAL `pnpm og`. Nothing forced anyone to
// run it, so a copy edit could ship with a stale card — that is how PR #325 left the old subtitle
// and the retired «1С» on the live image while the site already said otherwise.
//
// The generator writes this stamp next to the PNG; `tests/ogStamp.test.ts` recomputes it from the
// current sources and fails when they diverge, i.e. «you edited the copy, re-run pnpm og».
// Deliberately NOT mtime-based: git does not preserve modification times, so after a fresh clone
// (every CI run) the PNG and its inputs are all equally «new» and such a guard proves nothing.
//
// Shared by the generator and the test so the hash cannot be computed two slightly different ways.
export function ogStamp(input) {
  const canonical = JSON.stringify({
    title: input.title,
    subtitle: input.subtitle,
    formats: input.formats,
    badge: input.badge
  })
  return { hash: createHash('sha256').update(canonical).digest('hex') }
}
